// Generated by IB v0.7.2 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <WatchKit/WatchKit.h>
#import <Foundation/Foundation.h>
#import <WatchConnectivity/WatchConnectivity.h>

@interface ExtensionDelegate: NSObject
-(IBAction) applicationDidFinishLaunching;
-(IBAction) applicationDidBecomeActive;
-(IBAction) applicationWillResignActive;

@end

@interface GlanceController: WKInterfaceController
-(IBAction) awakeWithContext:(id) context;
-(IBAction) willActivate;
-(IBAction) didDeactivate;

@end

@interface InterfaceController: WKInterfaceController

@property IBOutlet WKInterfaceTable * watchTable;

-(IBAction) awakeWithContext:(id) context;
-(IBAction) willActivate;
-(IBAction) didDeactivate;

@end

@interface NotificationController: WKUserNotificationInterfaceController
-(IBAction) init;
-(IBAction) willActivate;
-(IBAction) didDeactivate;

@end

@interface DummyWatchRowController: NSObject

@property IBOutlet WKInterfaceLabel * headline;

@end

